function skillsMember() {
    return [
        { id: 1, name: 'HTML' },
        { id: 2, name: 'CSS' },
        { id: 3, name: 'Javascript' },
        { id: 4, name: 'React' },
        { id: 5, name: 'Nodejs' },
        { id: 6, name: 'Express' },
        { id: 7, name: 'MongoDB' },
        { id: 8, name: 'SQL' },
        { id: 9, name: 'Python' },
        { id: 10, name: 'Django' },
        { id: 11, name: 'Flask' },
        { id: 12, name: 'Java' },
        { id: 13, name: 'Spring' },
        { id: 14, name: 'C#' },
        { id: 15, name: 'ASP.NET' },
        { id: 16, name: 'PHP' },
        { id: 17, name: 'Laravel' },
        { id: 18, name: 'Ruby' },
        { id: 19, name: 'Ruby on Rails' },
        { id: 20, name: 'Swift' },
        { id: 21, name: 'Kotlin' },
        { id: 22, name: 'Flutter' },
        { id: 23, name: 'Dart' },
        { id: 24, name: 'C++' },
        { id: 25, name: 'C' },
        { id: 26, name: 'R' },
        { id: 27, name: 'Go' },
        { id: 28, name: 'Scala' },
        { id: 29, name: 'Ruby' },
        { id: 30, name: 'Rust' },
        { id: 31, name: 'Haskell' },
        { id: 32, name: 'Erlang' },
        { id: 33, name: 'Lua' },
        { id: 34, name: 'Perl' },
        { id: 35, name: 'Bash' },
        { id: 36, name: 'Shell' },
        { id: 37, name: 'PowerShell
}